logging:
  config: classpath:logback-spring.xml
  level:
    com.cbrc.plato.core.basic.dao: debug

spring:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.124.90.211:3306/user_data?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: root_123
    user:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.124.90.211:3306/user_data?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: root_123

  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: file:D://fileManager//static/

  redis:
    host: 10.124.90.211
    port: 6379
    password: root_123
    timeout: 36000
    jedis:
      pool:
        max-idle: 8
        max-total: 0
        max-active: 8
        max-wait: 1000
        idea-time: 300000  #最小空闲时间

  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

  shiro:
    properties:
      authz: false
    session-id-cookie:
      http-only: false
      name: yui2-token
      maxAge: 2592000
    session-dao:
      #expire: 86400 选用globalSessionTimeout这个值
      session-prefix: yui2-sid
    session-mgr:
      globalSessionTimeout: 86400000
    shiro-db-realm:
      authentication-caching-enabled: false
      authorization-caching-enabled: false
      authentication-cache-name: yui2-cache-authc
      authorization-cache-name: yui2-cache-authz
  http:

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


shiro:
  session:
    #shiro session前缀
    session-prefix : "shiro-redis-session"
    #shiro session 在redis过期时间是(分钟)
    session-time : 1800
  cache:
    #shiro缓存前缀
    cache-prefix : "shiro-redis-cache"
    #shiro缓存在redis过期时间是(分钟)
    cache-time : 180

#JWT配置
jwt:
  ##认证名称
  header : "authorization"
  ##加密向量
  secret : "1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"
  ##token过期时间一天(秒)
  expiration : 7200
  ##refresh_token过期时间一天(秒)
  refresh_expiration : 86400
  ##Tokenu前缀
  token.head : "Bearer"

